version: '3.8'

services:
  api:
    container_name: pet_watch_api
    build: ./api
    ports:
      - 8000:5000
    volumes:
      - ./api:/api
    env_file:
      - ./api/.env.docker.dev
    depends_on:
      db:
        condition: service_healthy

  app:
    container_name: pet_watch_app
    build: ./pet_watch_app
    ports:
      - 8100:5000
    volumes:
      - ./pet_watch_app:/app
    env_file:
      - ./pet_watch_app/.env.docker.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chanchtemps
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
