version: '3.8'

services:
  api:
    container_name: pet_watch_api
    build:
      context: ./
      dockerfile: ./api/Dockerfile.api.dev
    command: bash -c "cp models.py api && python api/wsgi.py"
    ports:
      - 8100:5000
    volumes:
      - ./:/api
    env_file:
      - ./api/.env.dev
    depends_on:
      db:
        condition: service_healthy

  app:
    container_name: pet_watch_app
    build:
      context: ./
      dockerfile: ./pet_watch_app/Dockerfile.app.dev
    command: bash -c "cp models.py pet_watch_app && python pet_watch_app/wsgi.py"
    ports:
      - 8000:5000
    volumes:
      - ./:/app
    env_file:
      - ./pet_watch_app/.env.dev
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.5-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chanchtemps
      - TZ=America/New_York
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data:
